name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Create dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipreqs
        pipreqs ./
    - name: Install dependencies
      run: |
        pip3 install torch==1.3.1+cpu torchvision==0.4.2+cpu -f https://download.pytorch.org/whl/torch_stable.html
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
